### ISSUE TITLE
Design UI Mockups

### ISSUE THREAD

**Issue by kumararoosh** [Find-A-Can/Find-A-Can#3]
Now that we have a distinct outline for our desired features, we need to design a User Interface that can facilitate all of the features

**Comment by ubelhj** [comment]
First UI Mockups for the project
[https://marvelapp.com/prototype/59bj04c](https://marvelapp.com/prototype/59bj04c)

**Comment by ubelhj** [comment]
We're confident this is all the interaction necessary to meet our minimum viable product. Any improvements to style or functionality will be decided on later given additional time.
