### ISSUE TITLE
Tests fail on main branch

### ISSUE THREAD

**Issue by BenjaminLowry** [Find-A-Can/Find-A-Can#42]
Hello Find-A-Can team,

I am Ben, one of your peer reviewers. I was able to build and run the backend using the instructions in the developer documentation. However, when I ran the tests via `gradle test` they failed for the following reasons when running the linter:

```
> eslint .


/Users/lowryb1/Downloads/Find-A-Can/FACBackEnd/src/main.js
  61:62   error  'toBoolean' is not defined           no-undef
  61:90   error  'toBoolean' is not defined           no-undef
  61:118  error  'toBoolean' is not defined           no-undef
  68:1    error  'toBoolean' is not defined           no-undef
  70:14   error  Expected '===' and instead saw '=='  eqeqeq
```

It seems there was a breaking change pushed the main branch about two hours ago. You are probably already aware of this, but just wanted to let you know that the tests failed for me on the current commit.

Thanks!

**Comment by kumararoosh** [comment]
Hi @BenjaminLowry,

Thank you for telling us about our breaking change. That code was mistakenly pushed in onto the main branch instead of one of our working branches, but that issue should be resolved now. We apologize for any difficulty this may have posed and appreciate your comment
